### ISSUE TITLE
New Rule not being enabled

### ISSUE THREAD

**Issue by TAINCER** [marirs/winfw-rs#8]
When creating a new Rule with `enabled` set to true, the actual rule is disabled. The other options are all set.

I Tested this on:
 - Windows 10 Version 22H2 (OS Build 19045.2251)
 - Windows Server 2019 Version 1809 (OS Build 17763.3650)

My Development Env:
 - rustc 1.65.0 (897e37553 2022-11-02)
 - Visual Studio Build Tools 2022 with ATL for latest v143 (x86 & x64)
 - Visual Studio Community 2022 with ATL for latest v143 (x86 & x64)
 - [anyhow](https://crates.io/crates/anyhow/1.0.66) 1.0.66
 - winfw 0.1.6

Example Code:
```rust
use anyhow::{Result, bail};
use winfw::{FwRule, Protocols, Actions, Directions, new_fw_rule};

fn setup_port_forwarding() -> Result<()> {
    let mut new_rule = FwRule::default();

    new_rule.name = "Test Rule".to_string();
    new_rule.interface_types = "LAN".to_string();
    new_rule.protocol = Protocols::Udp;
    new_rule.grouping = "Test Group".to_string();
    new_rule.action = Actions::Allow;
    new_rule.direction = Directions::In;
    new_rule.app_name = "C:\\my_program.exe".to_string();
    new_rule.enabled = true;

    if let Err(error) = new_fw_rule(&new_rule) {
        bail!(error);
    }

    Ok(())
}
```

**Comment by marirs** [comment]
Let me check and get back to you

**Comment by marirs** [comment]
@mnaza had made a small fix to have the rule enabled.
Could you include the latest version and check to see if it works as excepted now.

Thanks

**Comment by TAINCER** [comment]
Just tested it again. The Rule is enabled when `enabled` is set to true. The new `enable_fw_rule` also worked.

**Comment by marirs** [comment]
Thanks for reporting and the update!
